---
- command: docker inspect moxied
  register: moxied_inspect
  ignore_errors: True

- script: pull.py paultag moxie
  register: pull

- name: Update Moxie Daemon (docker)
  command: docker pull paultag/moxie
  when: pull.stdout.find('Yes') != -1

- name: Install Moxie Daemon Service
  copy: src=moxied.conf dest=/etc/init/moxied.conf owner=root group=root mode=0644
  # notify: restart

- name: Install Moxie Configuration
  copy: src=moxie.sh dest=/etc/docker/moxie.sh owner=root group=root mode=0644
  # notify: restart

- name: Apply Moxie Migrations
  script: migrate.sh
  when: pull.stdout.find('Yes') != -1

- name: Install Moxie Config
  copy: src=jobs.yml dest=/srv/docker/moxie/jobs.yml owner=root group=root mode=0644
  notify: Reload Moxie Config

- name: Stopping Moxie Daemon (docker)
  service: name=moxied state=stopped
  when: pull.stdout.find('Yes') != -1

- name: Purging Moxie Daemon (docker)
  command: docker rm moxied
  when: moxied_inspect.rc == 0
  when: pull.stdout.find('Yes') != -1

- name: Starting Moxie Daemon (docker)
  service: name=moxied state=started
  when: pull.stdout.find('Yes') != -1
